const emojiTypes = {
  faces: [
    { id: 1, emoji: '😀', desc: 'risonho' },
    { id: 2, emoji: '😁', desc: 'contente com olhos sorridentes' },
    { id: 3, emoji: '😂', desc: 'chorando de rir' },
    { id: 4, emoji: '🤣', desc: 'rolando no chão de rir' },
    { id: 5, emoji: '😃', desc: 'risonho com olhos bem abertos' },
    { id: 6, emoji: '😄', desc: 'risonho com olhos sorridentes' },
    { id: 7, emoji: '😅', desc: 'risonho com gota de suor' },
    { id: 8, emoji: '😆', desc: 'risonho com olhos semicerrados' },
    { id: 9, emoji: '😉', desc: 'com olho piscando' },
    { id: 10, emoji: '😊', desc: 'sorridente com olhos sorridentes' },
    { id: 11, emoji: '😋', desc: 'saboreando comida' },
    { id: 12, emoji: '😎', desc: 'sorridente com óculos escuros' },
    { id: 13, emoji: '😍', desc: 'sorridente com olhos de coração' },
    { id: 14, emoji: '😘', desc: 'mandando um beijo' },
    { id: 15, emoji: '🥰', desc: 'sorridente com 3 corações' },
    { id: 16, emoji: '😗', desc: 'beijando' },
    { id: 17, emoji: '😙', desc: 'beijando com olhos fechados' },
    { id: 18, emoji: '🥲', desc: 'sorridente com lágrima' },
  ],
  animals: [
    { id: 1, emoji: '🐶', desc: 'cachorro' },
    { id: 2, emoji: '🐱', desc: 'gato' },
    { id: 3, emoji: '🐭', desc: 'rato' },
    { id: 4, emoji: '🐹', desc: 'hamster' },
    { id: 5, emoji: '🐰', desc: 'coelho' },
    { id: 6, emoji: '🦊', desc: 'raposa' },
    { id: 7, emoji: '🐻', desc: 'urso' },
    { id: 8, emoji: '🐼', desc: 'panda' },
    { id: 9, emoji: '🦁', desc: 'leão' },
    { id: 10, emoji: '🐯', desc: 'tigre' },
    { id: 11, emoji: '🦓', desc: 'zebra' },
    { id: 12, emoji: '🦒', desc: 'girafa' },
    { id: 13, emoji: '🐘', desc: 'elefante' },
    { id: 14, emoji: '🐍', desc: 'cobra' },
    { id: 15, emoji: '🦋', desc: 'borboleta' },
    { id: 16, emoji: '🐦', desc: 'pássaro' },
    { id: 17, emoji: '🐧', desc: 'pingüim' },
    { id: 18, emoji: '🐢', desc: 'tartaruga' },
  ],
  objects: [
    { id: 1, emoji: '📱', desc: 'smartphone' },
    { id: 2, emoji: '💻', desc: 'computador portátil' },
    { id: 3, emoji: '📺', desc: 'televisão' },
    { id: 4, emoji: '🎧', desc: 'fones de ouvido' },
    { id: 5, emoji: '📷', desc: 'câmera' },
    { id: 6, emoji: '⌚', desc: 'relógio' },
    { id: 7, emoji: '🛴', desc: 'patinete' },
    { id: 8, emoji: '🚗', desc: 'carro' },
    { id: 9, emoji: '✈️', desc: 'avião' },
    { id: 10, emoji: '🚀', desc: 'foguete' },
    { id: 11, emoji: '🛳️', desc: 'navio' },
    { id: 12, emoji: '🏠', desc: 'casa' },
    { id: 13, emoji: '📚', desc: 'livros' },
    { id: 14, emoji: '🧳', desc: 'mala' },
    { id: 15, emoji: '🎒', desc: 'mochila' },
    { id: 16, emoji: '🧯', desc: 'extintor' },
    { id: 17, emoji: '🔦', desc: 'lanterna' },
    { id: 18, emoji: '⚽', desc: 'bola de futebol' },
  ],
  foods: [
    { id: 1, emoji: '🍏', desc: 'maçã verde' },
    { id: 2, emoji: '🍌', desc: 'banana' },
    { id: 3, emoji: '🍒', desc: 'cereja' },
    { id: 4, emoji: '🍓', desc: 'morango' },
    { id: 5, emoji: '🍉', desc: 'melancia' },
    { id: 6, emoji: '🍇', desc: 'uva' },
    { id: 7, emoji: '🍍', desc: 'abacaxi' },
    { id: 8, emoji: '🥭', desc: 'manga' },
    { id: 9, emoji: '🍅', desc: 'tomate' },
    { id: 10, emoji: '🥕', desc: 'cenoura' },
    { id: 11, emoji: '🥔', desc: 'batata' },
    { id: 12, emoji: '🌽', desc: 'milho' },
    { id: 13, emoji: '🍕', desc: 'pizza' },
    { id: 14, emoji: '🍔', desc: 'hambúrguer' },
    { id: 15, emoji: '🌭', desc: 'hot dog' },
    { id: 16, emoji: '🍣', desc: 'sushi' },
    { id: 17, emoji: '🍦', desc: 'sorvete' },
    { id: 18, emoji: '🍰', desc: 'bolo' },
  ],
};

export default emojiTypes;
